### ISSUE TITLE
Does this download the ebooks which is in subscriptions ? or only daily free ebook can be downloaded

### ISSUE THREAD

**Issue by BurnhamG** [BurnhamG/packtpub-downloader#13]
Does this download the ebooks which is in subscriptions ? or only daily free ebook can be downloaded

(Moved to separate issue)
_Originally posted by @Eddy300 in https://github.com/BurnhamG/packtpub-downloader/issues/5#issuecomment-681924913_

**Comment by BurnhamG** [comment]
This will only download the books that are marked as "owned" on the account, whether they were purchased or from a daily free offer.

**Comment by Eddy300** [comment]
> This will only download the books that are marked as "owned" on the account, whether they were purchased or from a daily free offer.

Alright, it would be great if that feature will also be added .

**Comment by BurnhamG** [comment]
Unfortunately that's not something I'm able to do. The API requires that the books have to marked as "owned" by the account, and with a subscription you're just paying for access to the books, rather than ownership of the books.
