### ISSUE TITLE
Tqdm.write type error 

### ISSUE THREAD

**Issue by BurnhamG** [BurnhamG/packtpub-downloader#3]
Again, courtesy of @Reiner030 [here](https://github.com/BurnhamG/packtpub-downloader/commit/38a771eec307fd1c110477a3503acbfa16510db2#commitcomment-35274110): 

> tdqm.write in line 143 has now some bug in giving out the error message:
> 
> ```
> ERROR (please copy and paste in the issue)
> Traceback (most recent call last):
>   File "packtpub-downloader-async/main.py", line 401, in <module>
>     main(sys.argv[1:])
>   File "packtpub-downloader-async/main.py", line 397, in main
>     separate, root_directory, quiet)
>   File "packtpub-downloader-async/main.py", line 228, in download_all_books
>     filenames, urls = enumerate_book_file_types(books_iter, book_file_types, root_directory, separate, user)
>   File "packtpub-downloader-async/main.py", line 266, in enumerate_book_file_types
>     file_types = get_book_file_types(user, book['productId'])
>   File "packtpub-downloader-async/main.py", line 143, in get_book_file_types
>     tqdm.write(r.json())
>   File "/home/reiner/.local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 517, in write
>     fp.write(s)
> TypeError: write() argument must be str, not dict
> ```
> 
> Before this change I got these error notifications:
> 
> ```
> ERROR (please copy and paste in the issue)
> {'message': 'No record Found', 'errorCode': 1001054, 'errorId': '63e61612-0377-4d01-9726-23240c82540e'}
> 404
> ERROR (please copy and paste in the issue)
> {'message': 'No record Found', 'errorCode': 1001054, 'errorId': '08e14ee6-71c4-4bbc-89b8-2381075ae2b5'}
> 404
> ERROR (please copy and paste in the issue)
> {'message': 'No record Found', 'errorCode': 1001054, 'errorId': '30971689-a583-4f3e-a3e9-184f304363fb'}
> 404
> ```

**Comment by Reiner030** [comment]
Hi,
thanks for both fixes.

You missed here a second place for the casting:
```
diff --git a/main.py b/main.py
index 4bba853..5a8ab11 100755
--- a/main.py
+++ b/main.py
@@ -140,8 +140,8 @@ def get_book_file_types(user, book_id):
         get_book_file_types(user, book_id)  # call recursive

     tqdm.write('ERROR (please copy and paste in the issue)')
-    tqdm.write(r.json())
-    tqdm.write(r.status_code)
+    tqdm.write(str(r.json()))
+    tqdm.write(str(r.status_code))
     return []


```

With this fix my run is "fine" again and give again these error notifications as before:
```
ERROR (please copy and paste in the issue)
{'message': 'No record Found', 'errorCode': 1001054, 'errorId': '7a4e0dfb-95d0-494e-83e7-6590368e5c86'}
404
ERROR (please copy and paste in the issue)
{'message': 'Internal server error'}
502
ERROR (please copy and paste in the issue)
{'message': 'No record Found', 'errorCode': 1001054, 'errorId': '9adf909d-5968-489b-af7d-12163d8ea8dd'}
404
ERROR (please copy and paste in the issue)
{'message': 'No record Found', 'errorCode': 1001054, 'errorId': '96b0c23a-e82d-43e8-8d76-42b382fe0d43'}
404
```

**Comment by BurnhamG** [comment]
Thanks again, I've refactored to remove the duplicate code and the bug should be fixed.
