### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by jackyhjj** [BurnhamG/packtpub-downloader#5]
Hi, it seems that packt has modified the login system using recaptcha. Is there any solution to this ?

**Comment by BurnhamG** [comment]
Thanks for bringing this up! I heard about this issue and will definitely be taking a look at it ASAP.

**Comment by BurnhamG** [comment]
Hi @jackyhjj, I was taking a look and haven't run into any issues with a recaptcha on my end. What kind of problems are you seeing?

**Comment by jackyhjj** [comment]
Hi, it seems that it is working now because of the free week for black friday promotion. Will try again next week when it ends. Thanks!

**Comment by jackyhjj** [comment]
Hi, It is working fine even after the promotion weeks end. Thanks a lot!

**Comment by jackyhjj** [comment]
Hi @BurnhamG , i have this error when I try to run the download command today. 

I haven't changed any password or email command, been using it copy and paste. And now there is an error logging in.

<img width="726" alt="Screen Shot 2019-12-27 at 21 29 18" src="https://user-images.githubusercontent.com/7055599/71520704-f4592880-28ef-11ea-8f91-5ca8524e1459.png">

**Comment by BurnhamG** [comment]
Hi @jackyhjj, thanks for letting me know about this! I'll take a look at let you know what I find. What branch are you using?

**Comment by jackyhjj** [comment]
Hi @BurnhamG , I am using the master branch.

**Comment by BurnhamG** [comment]
Thanks again, @jackyhjj , I really appreciate it. I was able to run the master branch without any problems, though I have fixed the error of an undefined variable. Try running it again, and this time it should give you the actual error code if you have problems logging in.

**Comment by jackyhjj** [comment]
hi @BurnhamG , happy new year 2020! I am able to login again now. It seems that the login function with recaptcha is not always applied on packt server. But occasionally, they will activate recaptcha function upon login. Cheers! thanks for your update.

**Comment by BurnhamG** [comment]
Happy New Year! I'm glad to hear that it works again - I know a lot of people have been experiencing login issues due to the captcha, so I'll investigate ways of handling this in the script.

**Comment by jackyhjj** [comment]
well, i have been browsing around and found this repo issue [packt_recaptcha_issue](https://github.com/luk6xff/Packt-Publishing-Free-Learning/issues/172) it seems that they use an anti-captcha service to handle that. It might give you some insights. Cheers!

**Comment by Eddy300** [comment]
Does this download the ebooks which is in subscriptions ? or only daily free ebook can be downloaded
